import { Resend } from 'resend'
import { createServerClient } from '@/lib/supabase/server'
import { renderInvoiceHtml } from '@/lib/invoice/template'

/**
 * Creates an invoice record and sends it to the customer.
 * Idempotent — if an invoice for this booking already exists, does nothing.
 */
export async function createInvoice(bookingId: string): Promise<void> {
  const supabase = createServerClient()

  // Idempotency check
  const { data: existing } = await supabase
    .from('invoices')
    .select('id')
    .eq('booking_id', bookingId)
    .maybeSingle()

  if (existing) return

  // Fetch booking with tour info
  const { data: booking, error: bookingErr } = await supabase
    .from('bookings')
    .select(`
      id, customer_name, customer_email, customer_phone,
      num_pax, total_price, fomo_order_id, payment_status,
      tour_date:tour_dates (
        date,
        tour:tours ( name, price )
      )
    `)
    .eq('id', bookingId)
    .single()

  if (bookingErr || !booking) {
    console.error('[invoice] booking fetch failed', bookingErr?.message)
    return
  }

  const tourDate = booking.tour_date as {
    date: string
    tour: { name: string; price: number }
  } | null

  const tourName = tourDate?.tour?.name ?? 'Tour'
  const tourDateStr = tourDate?.date
    ? new Intl.DateTimeFormat('en-SG', { day: '2-digit', month: 'short', year: 'numeric' }).format(
        new Date(tourDate.date + 'T00:00:00')
      )
    : '—'

  const unitPrice = tourDate?.tour?.price ?? (booking.total_price / booking.num_pax)
  const invoiceDateStr = new Intl.DateTimeFormat('en-SG', {
    day: '2-digit', month: 'short', year: 'numeric',
  }).format(new Date())

  // Insert invoice row (invoice_number auto-generated by DB sequence)
  const { data: invoice, error: insertErr } = await supabase
    .from('invoices')
    .insert({
      booking_id:     bookingId,
      customer_name:  booking.customer_name,
      customer_email: booking.customer_email,
      customer_phone: booking.customer_phone ?? null,
      tour_name:      tourName,
      tour_date:      tourDate?.date ?? null,
      num_pax:        booking.num_pax,
      unit_price:     unitPrice,
      total_price:    booking.total_price,
      payment_status: booking.payment_status ?? 'paid',
      transaction_ref: booking.fomo_order_id ?? null,
    })
    .select('id, invoice_number')
    .single()

  if (insertErr || !invoice) {
    console.error('[invoice] insert failed', insertErr?.message)
    return
  }

  // Send email
  const apiKey = process.env.RESEND_API_KEY
  if (!apiKey) {
    console.warn('[invoice] RESEND_API_KEY not set — skipping email')
    return
  }

  const html = renderInvoiceHtml({
    invoiceNumber:  invoice.invoice_number,
    invoiceDate:    invoiceDateStr,
    paymentStatus:  (booking.payment_status === 'paid' ? 'paid' : 'pending'),
    customerName:   booking.customer_name,
    customerEmail:  booking.customer_email,
    customerPhone:  booking.customer_phone ?? '',
    tourName,
    tourDate:       tourDateStr,
    numPax:         booking.num_pax,
    unitPrice,
    totalPrice:     booking.total_price,
    transactionRef: booking.fomo_order_id,
  })

  const from = process.env.RESEND_FROM_EMAIL ?? 'Awesome Travel <invoices@sgawesometravel.com>'

  const resend = new Resend(apiKey)
  const { error: emailErr } = await resend.emails.send({
    from,
    to: booking.customer_email,
    subject: `Your Invoice ${invoice.invoice_number} – ${tourName}`,
    html,
  })

  if (emailErr) {
    console.error('[invoice] email send failed', emailErr)
    return
  }

  await supabase
    .from('invoices')
    .update({ email_sent: true })
    .eq('id', invoice.id)
}
